### ISSUE TITLE
Referencing external dependencies/assets

### ISSUE THREAD

**Issue by kristianmandrup** [lasso-js/lasso#60]
Is it possible to reference external assets via lasso and have them bundled as well?

All the examples seem to be of the form `"./jquery.js"` but what if we want to use CDN assets or assets stored on Amazon S3 etc. Can we incorporate our own URI loader in order to retrieve "protected assets" on a private server etc.? 

Thanks :)

**Comment by patrick-steele-idem** [comment]
Lasso.js does allow referencing external JS files in your `browser.json` files. You can do the following:

```json
{
    "dependencies": [
        "https://code.jquery.com/jquery-2.1.4.min.js"
    ]
}
```

That will result in jQuery being downloaded from the jQuery CDN (instead of being bundled with the other JS code).

You can also do the following:

```json
{
    "dependencies": [
        {
            "path": "https://code.jquery.com/jquery-2.1.4.min.js",
            "external": false
        }    
    ]
}
```

That will result in jQuery being downloaded from the CDN and bundled with all of the other JS code for the app. Since `external` is set to `false` in this example it will not be served up by the jQuery CDN.

Here's the relevant code in Lasso.js: https://github.com/lasso-js/lasso/blob/master/lib/dependencies/dependency-resource.js 

We do need to make this clearer in the docs. Thanks for bringing this up. Does this address your concerns?

**Comment by kristianmandrup** [comment]
Hi @patrick-steele-idem :) Thanks a lot! This is exactly what I was asking for and now my prayers are answered :) Yes, please update the docs to make it clear that external refs are an option as well :)
Also include the `external` option (and any other missing options) in the docs :)
Love your quick feedback and beautiful libs!

**Comment by patrick-steele-idem** [comment]
New documentation added: [External Dependencies](https://github.com/lasso-js/lasso#external-dependencies)

Please let us know if you find anything else that is missing. Thanks!

**Comment by tindli** [comment]
I like the new docs! :+1: 

Is there/should there be a way to allow external deps having a name - like you can give to bundles?

I am asking because when an external dependency only adds its data to the "window" namespace,
and you use this global symbol within a widget it is not very explicit where this symbol
really originates...

So there are basically 2 issues here:
1. is there a way to give external dependencies a name that can be used within a widget via require()? (if yes, we should update the docs)
2. if not, how do you feel if a widget depends on/uses a global symbol...

**Comment by tindli** [comment]
ok my statement above.... is obsolete....

According to @patrick-steele-idem it is better to wrap global dependencies as modules.

**Comment by kristianmandrup** [comment]
Thanks a lot guys :) Please keep making the docs a little better... I know there is a lot to cover
