### ISSUE TITLE
Allow minification to only be enabled for inline resources

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso#84]
I am not using the lasso minification, and instead relying on a plugin to upload the resources to a CDN which handles minification. However, for resources that are not uploaded to the CDN (inline js), I would like to be able to use lasso minification. Currently the config `minify` setting applies to all resources, so I can't use it. 

Would it make sense to add additional lasso options for more granularity in minification? Or would a plugin be the better route?

**Comment by patrick-steele-idem** [comment]
I think that makes sense to extend the existing minfication plugins. Do you have any thoughts on what an appropriate configuration option would be? `minifyInlineOnly: true`? Alternatively, we could provide a more flexible `shouldMinify(code, lassoContext)` extension instead of a very specific configuration option. Thoughts?

Also, the `lassoContext` arguments will contain a reference to the dependency using `lassoContext.dependency` and the `lassoContext.dependency.inline` property could be used to determine if the dependency is inline or not.

**Comment by yomed** [comment]
I see that we have undocumented `minifyJS` and `minifyCSS`, so maybe throwing in an extra `minifyInlineJS` isn't so bad. Since everything is handled through configuration, I think this makes sense. Though if we have more usecases pop up in the future, `shouldMinify` would certainly open up the possibilities. How would we use code in `shouldMinify` rather than config?

**Comment by patrick-steele-idem** [comment]
The `shouldMinify(code, lassoContext)` function could, in theory, be registered by a plugin. If there is a plugin that is being registered to externalize resources then that plugin could also register the `shouldMinify(code, lassoContext)` function so that no configuration has to change for anyone that is already using that plugin and inline JS and CSS would automatically be minified. I think that is the way to go.

**Comment by yomed** [comment]
What about if multiple plugins register `shouldMinify`? Seems like there could be some risk in plugins conflicting with each other.

**Comment by patrick-steele-idem** [comment]
Multiple `shouldMinify` functions is an edge case but I think that can be reasonably accommodated by defining the rules and maybe allowing each `shouldMinify()` to return one of three values:

- `undefined` - don't care, use default
- `false` - definitely don't minify 
- `true` - minify as long as no  other `shouldMinify` returned `false`

Seem reasonable?

**Comment by RajaRamu** [comment]
can we use Comment line like //JsDoNotOptimize on top the JS file like before.

**Comment by patrick-steele-idem** [comment]
@RajaRamu That's a good suggestion for a separate feature. Do you mind opening a Github issue? Also, is `//JsDoNotOptimize` the standard identifier?

**Comment by RajaRamu** [comment]
@patrick-steele-idem  - i don't know how standard this flag is (JsDoNotOptimize). Industry standard would be,
{
path:'/.myjs.js'
optimize: "none"
}

**Comment by yomed** [comment]
@patrick-steele-idem I made a small plugin to quickly take care of this for an upcoming production run. Do you see any problem with doing it this way? https://github.com/yomed/lasso-minify-inline-js

**Comment by patrick-steele-idem** [comment]
Hey @yomed, I don't see any issues with your solution, but probably better to merge this functionality into the core minification plugin and introduce a new configuration option. That way we only need to maintain one minifier. Thoughts?

**Comment by yomed** [comment]
Oh, that would be ok with me. I wasn't sure if you still wanted to go after the more generic solution of having plugins register a `shouldMinify` function which would then go through the regular lasso pipeline.

**Comment by patrick-steele-idem** [comment]
I'm good with supporting a `minifyInlineOnly: true` option for the [lasso-minify-js](https://github.com/lasso-js/lasso-minify-js). Currently we don't support a clean way to provide configuration option for the builtin `lasso-minify-js` plugin so please go forward with your solution for now. I think we need to fix this is in `lasso@^2`, but I would prefer not backporting the patch to `lasso@^1` since it is a new feature and not a bug fix.

**Comment by yomed** [comment]
Sounds good, I can migrate over once all of that is in place

**Comment by patrick-steele-idem** [comment]
New version published for lasso v2: `lasso@2.3.0`

Backport to lasso v1 coming soon. I will update here when available.

**Comment by patrick-steele-idem** [comment]
New version published for lasso v1: `lasso@1.18.0`
