### ISSUE TITLE
Cache not being busted on dependency changes

### ISSUE THREAD

**Issue by cosminonea** [lasso-js/lasso#88]
If I change a page dependency, like a css file, the cache is not being refreshed and the new css file and the fingerprint are not re-generated.

Is this as expected?

**Comment by patrick-steele-idem** [comment]
Hey @cosminonea, we should definitely discuss this in the docs, but lasso does _not_ start a file watcher to watch for changes to files and caches everything by default. However, to bust the cache you can start your own file watching service and then call the following API method whenever a file is modified:

```javascript
require('lasso').handleWatchedFileChanged(filename);
```

This will result in internal caches being flushed and then the next time you refresh the page or use lasso to generate JS and CSS files then you will see everything re-generated as expected.

However, I strongly recommend using the [browser-refresh](https://github.com/patrick-steele-idem/browser-refresh) Node.js process launcher. It can be used used a drop-in replacement for the `node` command, but it has the added benefit that it starts a file watching service and it starts a WebSocket server. `browser-refresh` gives you instant browser refreshing of JS, CSS, images, etc., all without requiring a change to even a single line of code in your application. Lasso.js detects when your app is launched using `browser-refresh` and handles everything automatically (see: https://github.com/lasso-js/lasso/blob/master/browser-refresh/index.js).

Does that work for you? Let us know if you still have questions.

**Comment by cosminonea** [comment]
@patrick-steele-idem thanks for that. I think that is exactly what I need.

I am talking about a cloud deployment not development. No sure if you are familiar with Azure but I am using the continuous deployment feature of the web apps which pulls all the changes from github and restarts the service. In this case, lasso wasn't refreshing the cache.

Thanks for the tip.

**Comment by patrick-steele-idem** [comment]
Hey @cosminonea, Lasso.js uses a combination of memory caches and disk caches by default (it is configurable). If you delete the `.cache/` directory in the root of the directory that will safely wipe out the disk caches used by Lasso.js. For every production deploy I recommend deleting the `.cache/` directory. Disk caches are helpful in production since they are still used even if the process restarts, but if you push out new code you should delete the `.cache/` directory.

FYI, here's the default cache config:

https://github.com/lasso-js/lasso/blob/f29332830aefa08c4b61ac5efdff380ee9364778/lib/LassoCache.js#L12-L53

You should configure the cache based on the environment that your app is in using an environment-specific configuration loader (such as [async-config](https://github.com/patrick-steele-idem/async-config)). If you aren't using an environment-specific configuration loader, you can do something similar to the following:

```javascript
require('lasso').configure({
        "cacheProfile": process.env.NODE_ENV === 'production' ? 'production' : 'development',
        ...
    });
```

Currently, there is no easy way to disable all disk caches so hopefully deleting the `.cache/` directory works for you. If not, let me know and we can discuss other options.

**Comment by cosminonea** [comment]
Deleting the disk cache folder will do it for now.

Ideally lasso, on configure() maybe, should walk through the cache and see if anything changed and invalidate the changed resources.

**Comment by patrick-steele-idem** [comment]
Hey @cosminonea, checking to see if files if the cache is up-to-date is very expensive since it requires hitting the file system a lot and it is something you typically want to avoid doing in production. You basically end up having to do all of the work over again just to find out if there is anything that needs to be invalidated. In production we want to assume that the cache is valid so that there is less CPU and I/O usage. The only reason the cache would not be valid would be when new code is pushed. If new code is pushed the easiest thing to do is to delete the `.cache/` directory when new code published. This definitely needs to be explained better somewhere in the docs. I'll open a Github issue. Thanks for opening the issue and glad deleting the `.cache/` folder works for you for now.
